"""tables

Revision ID: 765630939b20
Revises: 
Create Date: 2020-11-02 22:31:35.392693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765630939b20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_name', sa.String(length=128), nullable=True),
    sa.Column('ixlan_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_exchange_name'), 'exchange', ['exchange_name'], unique=False)
    op.create_index(op.f('ix_exchange_ixlan_id'), 'exchange', ['ixlan_id'], unique=True)
    op.create_table('peer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('asn', sa.Integer(), nullable=True),
    sa.Column('policy', sa.String(length=64), nullable=True),
    sa.Column('ipv4prefixes', sa.Integer(), nullable=True),
    sa.Column('ipv6prefixes', sa.Integer(), nullable=True),
    sa.Column('as_set', sa.String(length=32), nullable=True),
    sa.Column('peered_IPv4', sa.Boolean(), nullable=False),
    sa.Column('peered_IPv6', sa.Boolean(), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('ixlan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ixlan'], ['exchange.ixlan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_as_set'), 'peer', ['as_set'], unique=False)
    op.create_index(op.f('ix_peer_asn'), 'peer', ['asn'], unique=False)
    op.create_index(op.f('ix_peer_ipv4prefixes'), 'peer', ['ipv4prefixes'], unique=False)
    op.create_index(op.f('ix_peer_ipv6prefixes'), 'peer', ['ipv6prefixes'], unique=False)
    op.create_index(op.f('ix_peer_name'), 'peer', ['name'], unique=False)
    op.create_index(op.f('ix_peer_policy'), 'peer', ['policy'], unique=False)
    op.create_index(op.f('ix_peer_region'), 'peer', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peer_region'), table_name='peer')
    op.drop_index(op.f('ix_peer_policy'), table_name='peer')
    op.drop_index(op.f('ix_peer_name'), table_name='peer')
    op.drop_index(op.f('ix_peer_ipv6prefixes'), table_name='peer')
    op.drop_index(op.f('ix_peer_ipv4prefixes'), table_name='peer')
    op.drop_index(op.f('ix_peer_asn'), table_name='peer')
    op.drop_index(op.f('ix_peer_as_set'), table_name='peer')
    op.drop_table('peer')
    op.drop_index(op.f('ix_exchange_ixlan_id'), table_name='exchange')
    op.drop_index(op.f('ix_exchange_exchange_name'), table_name='exchange')
    op.drop_table('exchange')
    # ### end Alembic commands ###
