"""new router table

Revision ID: e1ff6ff71f4b
Revises: 765630939b20
Create Date: 2020-11-15 19:26:27.612801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ff6ff71f4b'
down_revision = '765630939b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('router',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('router_name', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_router_region'), 'router', ['region'], unique=False)
    op.create_index(op.f('ix_router_router_name'), 'router', ['router_name'], unique=True)
    op.add_column('exchange', sa.Column('router', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exchange', 'router', ['router'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exchange', type_='foreignkey')
    op.drop_column('exchange', 'router')
    op.drop_index(op.f('ix_router_router_name'), table_name='router')
    op.drop_index(op.f('ix_router_region'), table_name='router')
    op.drop_table('router')
    # ### end Alembic commands ###
